# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 10:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateTestApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(choices=[('ytk.yuantiku.ws', '\u6d4b\u8bd5\u73af\u5883'), ('www.yuantiku.com', '\u7ebf\u4e0a\u73af\u5883')], max_length=20)),
                ('base_url', models.TextField(verbose_name='URL')),
                ('method', models.CharField(choices=[('POST', 'POST'), ('GET', 'GET')], max_length=10)),
                ('header', models.TextField(verbose_name='header')),
                ('body', models.TextField(verbose_name='body')),
                ('description', models.TextField(verbose_name='Case\u63cf\u8ff0')),
                ('assertion', models.CharField(choices=[('\u7b49\u4e8e', '\u7b49\u4e8e'), ('\u4e0d\u7b49\u4e8e', '\u4e0d\u7b49\u4e8e'), ('\u5305\u542b', '\u5305\u542b')], max_length=6)),
                ('value_assertion', models.TextField(verbose_name='\u65ad\u8a00\u503c')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u65b0\u5efa\u63a5\u53e3',
                'verbose_name_plural': '\u65b0\u5efa\u63a5\u53e3',
            },
        ),
        migrations.CreateModel(
            name='MicroService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('micro_service', models.CharField(max_length=64, verbose_name='\u5fae\u670d\u52a1')),
            ],
            options={
                'verbose_name': '\u5fae\u670d\u52a1',
                'verbose_name_plural': '\u5fae\u670d\u52a1',
            },
        ),
        migrations.CreateModel(
            name='StatusCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.CharField(max_length=10, verbose_name='\u72b6\u6001\u7801')),
            ],
            options={
                'verbose_name': '\u72b6\u6001\u7801',
                'verbose_name_plural': '\u72b6\u6001\u7801',
            },
        ),
        migrations.AddField(
            model_name='createtestapi',
            name='micro_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.MicroService'),
        ),
        migrations.AddField(
            model_name='createtestapi',
            name='status_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.StatusCode'),
        ),
    ]
