# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='microservice',
            name='service_name',
            field=models.CharField(default='\u9898\u5e93\u4e3b\u670d\u52a1', max_length=64, verbose_name='\u670d\u52a1\u540d'),
            preserve_default=False,
        ),
    ]
