# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_microservice_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createtestapi',
            name='assertion',
            field=models.CharField(choices=[('\u7b49\u4e8e', '\u7b49\u4e8e'), ('\u4e0d\u7b49\u4e8e', '\u4e0d\u7b49\u4e8e'), ('\u5305\u542b', '\u5305\u542b')], default='\u5305\u542b', max_length=6),
        ),
        migrations.AlterField(
            model_name='createtestapi',
            name='base_url',
            field=models.CharField(max_length=60, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='createtestapi',
            name='method',
            field=models.CharField(choices=[('POST', 'POST'), ('GET', 'GET')], default='GET', max_length=10),
        ),
        migrations.AlterField(
            model_name='createtestapi',
            name='status_code',
            field=models.ForeignKey(default='200', on_delete=django.db.models.deletion.CASCADE, to='index.StatusCode'),
        ),
    ]
