# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20170515_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createtestapi',
            name='assertion',
            field=models.CharField(choices=[('\u7b49\u4e8e', '\u7b49\u4e8e'), ('\u4e0d\u7b49\u4e8e', '\u4e0d\u7b49\u4e8e'), ('\u5305\u542b', '\u5305\u542b')], max_length=6),
        ),
        migrations.AlterField(
            model_name='createtestapi',
            name='status_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.StatusCode'),
        ),
    ]
